name: github release
on:
  push:
    paths-ignore:
      - README.md
      - docs/readme.md
      - docs/readme.rst
    branches:
      - master
jobs:
  shell-ci:
    uses: QualiSystems/.github/.github/workflows/shell-py-37-39.yml@master
  github-release:
    needs: shell-ci
    uses: QualiSystems/.github/.github/workflows/shell-github-release.yml@master
