name: CI

on:
  push:
    paths-ignore:
      - "README.md"
      - "docs/readme.md"
      - "docs/readme.rst"
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/readme.md"
      - "docs/readme.rst"
  release:
    types: [published]

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install pip -U
          pip install tox
      - name: Run pre-commit
        env:
          TOXENV: pre-commit
        run: tox
  pack:
    name: Pack the Shell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install pip -U
          pip install tox
      - name: Build
        env:
          TOXENV: pack
        run: tox
  check-version:
    name: Check version
    # only for PRs in master__old_code
    if: ${{ github.base_ref == 'master__old_code' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current version
        id: currentVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq e ".metadata.template_version" shell-definition.yaml
      - name: Save shell-definition.yaml from master
        run: |
          git clone https://github.com/${{ github.repository }}.git ${{ github.repository }}
          BASE_DIR=`pwd`
          cd ${{ github.repository }}
          git checkout -qf ${{ github.head_ref }}
          git show master__old_code:shell-definition.yaml > $BASE_DIR/tmp.yaml
      - name: Get master version
        id: masterVersion
        uses: mikefarah/yq@master
        with:
          cmd: yq e ".metadata.template_version" tmp.yaml
      - name: Check version
        run: |
          ! diff <(echo "${{ steps.currentVersion.outputs.result }}") <(echo "${{ steps.masterVersion.outputs.result }}")
  check-not-shell-in-shell-name:
    name: Check "Shell" is not in the Shell name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: get Node Type
        id: getNodeType
        uses: mikefarah/yq@master
        with:
          cmd: yq e ".node_types | keys | .[0]" shell-definition.yaml
      - name: Check shell is not in the Shell name
        run: |
          NODE_TYPE="${{ steps.getNodeType.outputs.result }}"
          SHELL_NAME=`echo ${NODE_TYPE:16} | tr "[:upper:]" "[:lower:]"`
          if [[ $SHELL_NAME == *" shell "* ]]
          then
            echo "You should remove 'Shell' from the Shell name"
            exit 1
          else
            echo "not found"
          fi
  create-gh-release:
    needs: [pre-commit, pack]
    if: ${{ github.ref == 'refs/heads/master__old_code' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          sudo apt-get -y install jq
          python -m pip install pip -U
          pip install tox yq
      - name: Pack and download dependencies
        run: tox
      - name: Set envs
        run: |
          version="$(yq -r .metadata.template_version shell-definition.yaml)"
          repo_owner=${{ github.repository }}
          index=`expr index "$repo_owner" /`
          repo=${repo_owner:index}
          echo "TAG=$version" >> $GITHUB_ENV
          echo "REPO=$repo" >> $GITHUB_ENV
      - name: Rename dependencies
        run: |
          mv dist/dependencies-win32.zip dist/cloudshell-$REPO-dependencies-win32-package-$TAG.zip
          mv dist/dependencies-linux.zip dist/cloudshell-$REPO-dependencies-linux-package-$TAG.zip
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "dist/*"
          draft: true
          name: ${{ env.REPO }} ${{ env.TAG }}
          tag: ${{ env.TAG }}
          commit: master__old_code
